language: node_js
node_js:
- 12
deploy:
  provider: heroku
  api_key:
    secure: cdWhAfpL1DW20FOARzmQQiaBgH6mtokVJgNu5ii8ylZhpKb86tNiO9N/cTltCKLJOIpLfQF+9mznpljZNRdM8FMClJdxwoIcNsq89jmOjodHtrbP888xceWX/PXJREApv6cZAdL0GR3D3C1u9BF1xTCDf5tQyEwqziuDkV1C+9s2DmUZsegKayh3y6Xbacldyq7M7S6bt4EbrCoqJuKSEGjS+P5y/OHkilqMr3clFm/UyzLrgT7JDeBQY+9Kyj7vNv6QnFsl/dBvNUxf8Ko2br4QH+aAd78EetBOnhqtcqcmofgWDWskwDthHcwZcURM4icuNKyYEbkG3Cy+rYBxJi472YjCbL03dzpBreTkM3JEk9EW2jlsC6FnpBP8pRb11UZCuyqQNj+cjHqZqNbeDwfa4wVXjrDvur0YYg0VyeeXpS7BswoFOr2dptbJIk4B9J4Fn1j21GrjfPP63iDoTjnh9kpmsbxAVgISJFlauQfVQN+xovV7aUGhA6LTFs0Pm8HDae5bA7XZ3S//CD2r+cmGJdR6loFnFrYzw3YslWcN8ROospU26dgnrysMU1Tp5JFBV7EcJHaOf7WySNWTAK6z5R9VDXKdeHmOVrXdboYFB1am2FIB1jtEcQlCLNUdzfs+Y/GlxdYe8W1GZ4j3s9SZP5yhHtZgdP6Jy8wOvCA=
  app: sara-discord